import 'dart:convert';

import 'package:flutter/material.dart';
import "package:demo/request/response.dart";
import 'package:demo/mode/listmode.dart';
class HomePage extends StatefulWidget {
  // String _title;
  // HomePage(this._title);
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
   var autogenerated;
   var listlength;
   _handleGetShelf () async {
   var res =await dio.get("/list");
   Map<String, dynamic> json = jsonDecode(res.data); 
   Autogenerated autogenerated=Autogenerated.fromJson(json);
   setState(() {
     this.listlength=autogenerated.data.length;
     this.autogenerated=autogenerated.data;
   });
}
  
  Widget _buildListItem(BuildContext context, int index) {
    print(this.listlength);

    // return ListTile(
    //   title: newsItem['name'],
    //   subtitle: newsItem['age']
    // );
  }
  
  @override
  void initState() {
    super.initState();
    this._handleGetShelf();
  }
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
       home: ListView.builder(
         itemBuilder: this._buildListItem,
         itemCount: this.listlength,
         ),
    );
  }
}

class JSON {
}